# docker-compose.yml
version: '3.9'

networks:
  inception:

services:

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart : always
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
     - "3306:3306"
    volumes:
     - mariadb:/var/lib/mysql
    env_file: .env  
    networks:
        - inception

  wordpress:
    container_name: wordpress
    image: wordpresss:latest
    restart : always
    depends_on: 
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose: ["9000"]
    volumes:
     - wordpress:/var/www/html/wordpress
    env_file: .env
    networks:
        - inception

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx:latest
    depends_on :
      - wordpress
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always

volumes:

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/rolexx/data/mariadb

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/rolexx/data/wordpress