version: '3.9'

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - inception
    env_file: .env

  wordpress:
      container_name: "wordpress"
      build: ./requirements/wordpress
      volumes:
        - wordpress:/var/www/html
      restart: always
      expose:
        - "9000"
      networks:
        - inception
      env_file: .env
      depends_on:
        - mariadb

  nginx:
    container_name: "nginx"
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    env_file: .env
    depends_on:
      - wordpress

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/rvrignon/data/wordpress

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /home/rvrignon/data/mariadb
